version: "2"
run:
  tests: false
linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exhaustive
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret # https://github.com/alexkohler/nakedret?tab=readme-ov-file#purpose
    - noctx
    - prealloc
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace

